In [1]:
#arange
import numpy as np
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#reshape
arr=np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
#size
a.size

9

In [4]:
#len
len(a)

9

In [5]:
#datatype
a.dtype

dtype('int32')

In [6]:
#sort
s=np.random.randint(5,size=10)
s

array([4, 0, 1, 3, 0, 2, 4, 0, 1, 4])

In [7]:
np.sort(s)

array([0, 0, 0, 1, 1, 2, 3, 4, 4, 4])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#max
np.amax(a)

9

In [10]:
#mi
np.amin(a)

1

In [11]:
#insert
s = np.insert(a, 1, 9)
s

array([1, 9, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#delete
s = np.delete(a, 1)
s

array([1, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#append
arr1 = np.arange(5) 
arr1

array([0, 1, 2, 3, 4])

In [14]:
arr3 = np.append(arr1, a)
arr3

array([0, 1, 2, 3, 4, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#expo
out_array = np.exp(arr1)
out_array

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
#square
arr1

array([0, 1, 2, 3, 4])

In [17]:
np.square(arr1)

array([ 0,  1,  4,  9, 16])

In [18]:
#zeros
c = np.zeros([3, 3])
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#ones
c = np.ones([3, 3])
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr1

array([0, 1, 2, 3, 4])

In [21]:
#cos
cos_Values = np.cos(arr1)
cos_Values

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [22]:
#sin
sin_Values=np.sin(arr1)
sin_Values

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [23]:
#tan
tan_Values=np.tan(arr1)
tan_Values

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [24]:
#power
arr5 = [2, 2, 2, 2, 2] 
arr6 = [2, 3, 4, 5, 6] 
out = np.power(arr5, arr6) 
out

array([ 4,  8, 16, 32, 64])

In [25]:
#log
arr1

array([0, 1, 2, 3, 4])

In [26]:
out_array = np.log(arr1)
out_array

C:\Users\Admin\AppData\Local\Temp\ipykernel_182076\2059293532.py:1: RuntimeWarning: divide by zero encountered in log
  out_array = np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [27]:
#identity
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
#dig
a = np.matrix([[1, 21, 30],  
                 [63 ,434, 3],  
                 [54, 54, 56]])
a

matrix([[  1,  21,  30],
        [ 63, 434,   3],
        [ 54,  54,  56]])

In [29]:
np.diag(a)

array([  1, 434,  56])